### ISSUE TITLE
3.13.0

### ISSUE THREAD

**Issue by catchthemonster** [bluesheeptoken/CPT#112]
Hi Luis, hope all is well,

CPT will not install on 3.13.0

let me know if you need help to get this project to latest Python?
I tried with pip/cube/api/py-3.13.0/bin/pip3.13 install cpt
Collecting cpt
  Using cached cpt-1.3.4.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/cube/api/py-3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/cube/api/py-3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/cube/api/py-3.13.0/lib/python3.13t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-8f381l40/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8f381l40/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-8f381l40/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8f381l40/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.



Cython is installed, aka.
$ /cube/api/py-3.13.0/bin/pip3.13 install cython
Requirement already satisfied: cython in /cube/api/py-3.13.0/lib/python3.13t/site-packages (3.0.11)

running with setup.py also fails:
$ /cube/api/py-3.13.0/bin/python3.13 setup.py install
/cube/api/py-3.13.0/lib/python3.13t/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/cube/api/py-3.13.0/lib/python3.13t/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
cpt/alphabet.cpp:2052:80: error: ‘__pyx_vectorcallfunc’ has not been declared
 2052 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw);
      |                                                                                ^~~~~~~~~~~~~~~~~~~~
cpt/alphabet.cpp: In function ‘PyObject* __pyx_pf_3cpt_8alphabet_8Alphabet_16__richcmp__(__pyx_obj_3cpt_8alphabet_Alphabet*, PyObject*, PyObject*)’:
cpt/alphabet.cpp:1941:41: warning: ‘Py_OptimizeFlag’ is deprecated [-Wdeprecated-declarations]
 1941 |   #define __pyx_assertions_enabled()  (!Py_OptimizeFlag)
      |                                         ^~~~~~~~~~~~~~~
cpt/alphabet.cpp:1488:43: note: in definition of macro ‘unlikely’
 1488 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                           ^
cpt/alphabet.cpp:4277:18: note: in expansion of macro ‘__pyx_assertions_enabled’
 4277 |     if (unlikely(__pyx_assertions_enabled())) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /cube/api/py-3.13.0/include/python3.13t/Python.h:76,
                 from cpt/alphabet.cpp:38:
/cube/api/py-3.13.0/include/python3.13t/cpython/pydebug.h:13:37: note: declared here
   13 | Py_DEPRECATED(3.12) PyAPI_DATA(int) Py_OptimizeFlag;
      |                                     ^~~~~~~~~~~~~~~
cpt/alphabet.cpp: At global scope:
cpt/alphabet.cpp:8014:69: error: ‘__pyx_vectorcallfunc’ has not been declared
 8014 | static PyObject *__Pyx_PyVectorcall_FastCallDict_kw(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
      |                                                                     ^~~~~~~~~~~~~~~~~~~~
cpt/alphabet.cpp: In function ‘PyObject* __Pyx_PyVectorcall_FastCallDict_kw(PyObject*, int, PyObject* const*, size_t, PyObject*)’:
cpt/alphabet.cpp:8051:13: error: ‘vc’ cannot be used as a function
 8051 |     res = vc(func, newargs, nargs, kwnames);
      |           ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cpt/alphabet.cpp: At global scope:
cpt/alphabet.cpp:8059:80: error: ‘__pyx_vectorcallfunc’ has not been declared
 8059 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
      |                                                                                ^~~~~~~~~~~~~~~~~~~~
cpt/alphabet.cpp: In function ‘PyObject* __Pyx_PyVectorcall_FastCallDict(PyObject*, int, PyObject* const*, size_t, PyObject*)’:
cpt/alphabet.cpp:8062:18: error: ‘vc’ cannot be used as a function
 8062 |         return vc(func, args, nargs, NULL);
      |                ~~^~~~~~~~~~~~~~~~~~~~~~~~~
cpt/alphabet.cpp: In function ‘PyObject* __Pyx_CyFunction_CallAsMethod(PyObject*, PyObject*, PyObject*)’:
cpt/alphabet.cpp:8748:6: error: ‘__pyx_vectorcallfunc’ was not declared in this scope; did you mean ‘vectorcallfunc’?
 8748 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
      |      ^~~~~~~~~~~~~~~~~~~~
      |      vectorcallfunc
cpt/alphabet.cpp:8749:9: error: ‘vc’ was not declared in this scope
 8749 |     if (vc) {
      |         ^~
error: command '/usr/bin/g++' failed with exit code 1



Regards,

**Comment by bluesheeptoken** [comment]
Hey Sasha,
Hope everything is well too :)

I haven't followed the Python3.13,
I can make the PR to push on 3.13, but if you want to give it a shot, here is a [python3.12 PR](https://github.com/bluesheeptoken/CPT/commit/f492710bd87e465813026d444a4ac711522fe22c), I think with copied pasted this could be done easily (don't worry about windows, it's broken atm, and I don't put any energy into it because noone is using windows' wheel)

If you don't have time, I'll try to take some time this week-end or next weekend !
